[wokwi]
version = 1
gdbPort = 3333
firmware = "libreroaster.bin"

# Additional Wokwi configuration
[wokwi.build]
target = "riscv32imc-unknown-none-elf"
chip = "esp32c3"

[esp32c3]

# Coffee Roaster GPIO Configuration
[pin.GPIO2]
mode = "output"

[pin.GPIO3]
mode = "output"

[pin.GPIO4]
mode = "output"

[pin.GPIO5]
mode = "output"

[pin.GPIO6]
mode = "input"

[pin.GPIO7]
mode = "output"

[pin.GPIO8]
mode = "output"

# SPI Configuration
[spi.SPI2]
misoPin = "GPIO6"
mosiPin = "GPIO5"
clkPin = "GPIO7"